### ISSUE TITLE
GF don't load in Foruns

### ISSUE THREAD

**Issue by AdrianoCahete** [brainfoolong/greaterfield#10]
![dont_load-forum](https://cloud.githubusercontent.com/assets/37474/19823582/26f95bf2-9d48-11e6-8948-c2cbe0ca7995.PNG)

Firefox x64 @ Win10

Is already expected/known?

**Comment by brainfoolong** [comment]
Firefox is currently not well tested, i keep it on the list.

**Comment by AdrianoCahete** [comment]
Update with console log:

```
20:30:38.998 ReferenceError: BF is not defined  

gf.translations.load()gf.js:475
<anonymous>gf.js:728
gf.backend.receive()gf.js:602
<anonymous>gf.js:719
1gf.js:475:13
```
I received two another errors, but it's from forum itself (editor.js and typekit).

**Comment by brainfoolong** [comment]
I've added some fixes to master. Should work now.

**Comment by AdrianoCahete** [comment]
Fixed with latest version. :)
