### ISSUE TITLE
Activated Plugins Button stays off

### ISSUE THREAD

**Issue by I-MrFixIt-I** [brainfoolong/greaterfield#14]
The button to toggle a plugin is not working correctly, it's always off.

So when I activate the plugin everything is working fine, but when I close and reopen the community plugins window the button is still off (even after a reload of the page).

It looks like it's just the status of the button which is always off, the plugin itself is working fine.

**Comment by brainfoolong** [comment]
Should be fixed now.

**Comment by I-MrFixIt-I** [comment]
Working now as expected.
