### ISSUE TITLE
Uploading to Gallery

### ISSUE THREAD

**Issue by biggx01** [brainfoolong/greaterfield#22]
Every time I upload a emblem to gallery it creates a new close button without terminating the last.

http://imgur.com/xASEp0r

Also, can you add a Creator/Definition tag box for creators, so it is easier for people to find/sort specific emblems? It seems all the emblems could get out of hand without some kind of labeling system.

**Comment by brainfoolong** [comment]
I will look into it soon.

**Comment by brainfoolong** [comment]
Problem with duplicate close btn is solved in master branch. Tagging will come sometime later. I'll close this for now.
