### ISSUE TITLE
Api code / Source

### ISSUE THREAD

**Issue by zeeh1975** [brainfoolong/greaterfield#24]
There is a chance to get a copy of api source to get it running in a private server. I'm looking for a way to export BF1 emblems to get it in BF4

**Comment by brainfoolong** [comment]
Well, unfortunetely no. The server side source was not designed to be public. Sorry.

**Comment by zeeh1975** [comment]
Ok, I unferstand. You already figured out the battlefield 1 emblems api, can give some advise on that.

p.s.: sorry for youtube message I wrote both at the same time

**Comment by brainfoolong** [comment]
Sorry, i haven't done anything for that since a long time. I can't help you here.
