### ISSUE TITLE
Emblem Gallery

### ISSUE THREAD

**Issue by brainfoolong** [brainfoolong/greaterfield#3]
I plan again a easy to use emblem gallery. Post bugs and suggestions here.
- [x] import all bblog emblems
- [x] share emblems to greatefield gallery (via share button)
- [x] allow import from bf4
- [x] allow import from emblemsbf.com code
- [x] add filters for gallery (newest, most used)
- [x] hide often reported emblems

**Comment by AdrianoCahete** [comment]
Suggestion: ability to import from other BF games (f.e.: bf4 to bf1).
Seems to be liked from others too: [How do we import emblems from BF 4/Battlelog into BF 1/Companion?](https://forums.battlefield.com/en-us/discussion/38733/how-do-we-import-emblems-from-bf-4-battlelog-into-bf-1-companion)

**Comment by brainfoolong** [comment]
Yes, is on the plan. I will import all from the BBLog gallery also.

**Comment by brainfoolong** [comment]
First emblem gallery batch is in master.

**Comment by brainfoolong** [comment]
Update to allow import from BF4 or code
